import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '/styles/Home.module.css'
import { Canvas } from '@react-three/fiber'
const DynamicIcosahedron = dynamic(() => import('../components/icosahedron'), {ssr: false, })

const DynamicTorus = dynamic(() => import('../components/torus'), {ssr: false, })
// import Cone from '../components/cone'

const DynamicCone = dynamic(() => import('../components/cone'), {ssr: false, })

export default function About () {
  return(
  <>
    <Head>
    <title>About</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <h1 > About the Good Karma Music Festival </h1>
  <div className={styles.canvas}>
          <Canvas>
            <DynamicIcosahedron position={[5, 0, 0]}/>
            <DynamicTorus position = {[-4, -1, 0]} />
            <DynamicCone position = {[-5, 6, 0]} />
          </Canvas>

        </div>
  <p>
    Colorless green ideas sleep furiously. If your left toenail turns neon purple, it might contain the fetus of an alien cat species. Good night, Mr. Sledgehammer. Let the bed bugs eat your socks.
    <br />
    Yesterday, I tried to order a sandwich, but the bread was too soggy. If you turn the black motion around, the sky will disapprove of your intransigent femur.
  </p>
</>
  )
}