import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Canvas } from '@react-three/fiber'
import { TrackballControls } from '@react-three/drei'
import styles from '/styles/Home.module.css'
import { IconContext } from 'react-icons'
import { FaInstagram, FaFacebook, FaYoutube } from 'react-icons/fa'
const DynamicDodecahedron = dynamic(() => import('../components/dodecahedron'), {ssr: false, })

const style = {color: "#ff32ff", marginRight: "1rem", marginTop: "1rem"}



export default function Contact (event: Event) {

  return(
  <>
    <Head>
    <title>Contact</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.png" />

  </Head>
  <Canvas>
    <DynamicDodecahedron position={[0, 0, 0]}/>
    <TrackballControls />
  </Canvas>
  <h1 > Contact: </h1>
  <ul>
    <li>
      <i>For General Information & Inquiries: </i>
      info@goodkarmafest.com
    </li>
    <li>
      <i>For Booking & Sponsorship:</i> <br />Andy Ryan
      <br /> aryan@yicunity.org
      <br /> 661-607-7367
    </li>
    <li>
      <i>Social Media: </i>
      <br />
        <a href="https://www.instagram.com/goodkarmafest/">
            <FaInstagram style={style} />
        </a>
        <a href="https://www.facebook.com/goodkarmafest">
          <FaFacebook style={style} />
        </a>
        <a href="https://www.youtube.com/channel/UCuUn-Ww94kbU0a63BMbckCA">
          <FaYoutube style={style} />
        </a>
    </li>
  </ul>
</>
  )
}