import Head from 'next/head'
import style from '/styles/Home.module.css'
import { Canvas } from '@react-three/fiber'
import Faq from "react-faq-component";
import { TrackballControls } from '@react-three/drei';
import dynamic from 'next/dynamic'
const DynamicCapsule = dynamic(() => import('../components/capsule'), {ssr: false, })

const data = {
  title: "Frequently Asked Questions (FAQ)",
  rows: [
      {
          title: "Q. What accessibility provisions are in place at the venue?",
          content: `A. There will be ramps, ADA toilets, and a quiet space.`,
      },
      {
          title: "Q. Are the shows 21+?",
          content:
              "A. No. GKMAF is all-ages.",
      },
      {
          title: "Q. Will there be food?",
          content: `A. Yes. There will be several food trucks on-site. `,
      },
      {
          title: "Q. Where can I park?",
          content: `A. There will be limited parking next to the venue, as well as street parking.`,
      },
      {
        title: "Q. Will the skatepark be open?",
        content: `A. Yes.`,
    },
  ],

}

const styles = {
  bgColor: 'transparent',
  titleTextColor: '#ff32ff',
  titleTextSize: '48px',
  rowTitleColor: '#ff0000',
  rowTitleTextSize: 'large',
  rowContentColor: 'black',
  rowContentTextSize: '16px',
  rowContentPaddingTop: '5px',
  rowContentPaddingBottom: '5px',
  rowContentPaddingLeft: '25px',
  rowContentPaddingRight: '75px',
  arrowColor: "red",
  transitionDuration: "0.5s",
  timingFunc: "ease-in-out"
}

export default function faqSection (props: any) {


  return (
  <>
    <Head>
      <title>FAQ</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    <Canvas className={style.canvas}>
      <DynamicCapsule position={[0, 0, -10]} />
      <TrackballControls />
    </Canvas>
    <Faq
        {...props}
        id="faq"
        data={data}
        styles={styles}
      />
  </>
  )
}