import Head from 'next/head'
import styles from '/styles/Home.module.css'
import { Canvas } from '@react-three/fiber'
import React, { useState, useEffect} from 'react'
import Faq from "react-faq-component";
import dynamic from 'next/dynamic'
const DynamicCapsule = dynamic(() => import('../components/capsule'), {ssr: false, })

const data = {
  title: "Frequently Asked Questions (FAQ)",
  rows: [
      {
          title: "Q. Is water wet?",
          content: `A. Pylons are dry.`,
      },
      {
          title: "Q. Is mac and cheese available for purchase?",
          content:
              "A. It is only if you donate belly button lint.",
      },
      {
          title: "Q. Did Luigi Russolo have an udder protruding from his left kneecap?",
          content: `A. What do you think? `,
      },
      {
          title: "Q. Where can I buy witchcraft supplies in advance of the festival?",
          content: `A. You can find each of our vendors underneath either stage.`,
      },
      {
        title: "Q. Does it hurt the horse?",
        content: `A. No.`,
    },
  ],
};

const style = {
  bgColor: "transparent",
  titleTextColor: "blue",
  rowTitleColor: "red",
  // rowContentColor: 'grey',
  // arrowColor: "red",
};

const config = {
  // animate: true,
  // arrowIcon: "V",
  // tabFocus: true
};


export default function faqSection (props: any ) {


  return (
  <>
    <Head>
      <title>FAQ</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* <Canvas className={styles.canvas}>
      <DynamicCapsule />
    </Canvas> */}

    <div>
    <Faq
        data={data}
        style={style}
        config={config}
      />
    </div>
  </>
  )
}