import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import { Canvas } from '@react-three/fiber'
import Capsule from './capsule'
import Icosahedron from './icosahedron'
import Cone from './cone'
import Torus from './torus'

export default function Lineup () {
  return(
  <>
    <Head>
    <title>Lineup</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />

  </Head>

  <h1 > Lineup </h1>
    <div className={styles.canvas}>
          <Canvas>
            <Capsule position  = {[0, 0, 0]} />
          </Canvas>

        </div>

        <h2>Spatula x 4</h2>
        <p>
        Scraping frozen plutonium since age four,
        Spatula x 4 have been nominated for seven Razzie awards and two Grammys.
        Their newest single, The Misshapen Egg, has been streamed over 200 times at Walmart. You can often catch them chasing purple instrusive thoughts beachside.
        </p>

        <div className={styles.center}>
              <Image
                className={styles.logo}
                src="/placeholder-3.jpg"
                alt="Placeholder"
                width={1008}
                height={756}
                priority
              />
        </div>
        <h2>Sprocket Girls</h2>
        <p>
        Hailing from Picher, Oklahoma, the Sprocket Girls first debuted at Woodstock 99. They have since released fourteen studio albums, nine of which sold exactly 13 copies. Upcoming collaborations include a tour with one of Michael Jacksons leftover fingernails and a single with Frank Zappa.
        </p>

        <div className={styles.center}>
              <Image
                className={styles.logo}
                src="/pf.jpg"
                alt="Placeholder"
                width={1008}
                height={756}
                priority
              />
        </div>
        <h2>Pixelated Flesh</h2>
        <p>
        Greetings! I am a mammal who codes and plays the viola, mandolin, and keyboards. My goal is to expand the boundaries between our minds, artistic creation, science, and language by straddling the boundaries between them. I have performed and composed in a variety of settings, as well as worked in scientific environments. Many people told me to pick between STEM and music and I never quite completed this task. I strive to create new ways to consume music. Have a look around this page and adjacent ones.


        </p>

        <div className={styles.center}>
              <Image
                className={styles.logo}
                src="/placeholder-4.jpg"
                alt="Placeholder"
                width={1008}
                height={756}
                priority
              />
        </div>
        <h2>Marty Thee Stallion</h2>
        <p>
        Im a sausage-shaped 78, XX canine who was abandoned on a freeway in Southern California and rehomed twice before finding my forever home at the age of six months. I am a dachsweiler who can make at least 10 different noises and miraculously, have not yet destroyed my unicorn plush.


        </p>
</>
  )
}