import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'

export default function Shop () {
  return(
  <>
    <Head>
    <title>Shop</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />

  </Head>

  <h1 > Shop </h1>
  <ul>
    <li><a href="https://www.eventbrite.com/e/2x-monster-trucks-kansas-city-ks-saturday-april-29th-2023-tickets-575065766187?aff=ebdssbdestsearch" className={styles.card}>Purchase tickets here</a></li>
    <li><a href="https://heyrooted.com/products/peruvian-apple-cactus-cereus-repandus?variant=42049993408694&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gclid=CjwKCAjwitShBhA6EiwAq3RqAyZSebSmHMSwKkN9jWGi2M6CTXsKNkRkQSU6YJEA5hVfOGye-x4JjBoC8ZgQAvD_BwE" className={styles.card}>Purchase cacti here</a></li>
    <li><a href="https://www.mercari.com/us/item/m45521900381/" className={styles.card}>Purchase a doll here</a></li>
  </ul>
</>
  )
}