import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Canvas } from '@react-three/fiber'
import { TrackballControls } from '@react-three/drei'
const DynamicOctahedron = dynamic(() => import('../components/octahedron'), {ssr: false, })

export default function Contact (event: Event) {

  return(
  <>
    <Head>
    <title>Become a Sponsor</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.png" />

  </Head>

  <h1 > For Booking & Sponsorship: </h1>
  <ul>
    <li>
      <i>For Booking & Sponsorship:</i> <br />Andy Ryan
      <br /> aryan@yicunity.org
      <br /> 661-607-7367
    </li>
  </ul>
  <Canvas>
    <DynamicOctahedron position={[0, 0, 0]}/>
    <TrackballControls />
  </Canvas>
</>
  )
}