import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function About () {
  return(
  <>
    <Head>
    <title>About</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet" />

  </Head>

  <h1 > About the Good Karma Music Festival </h1>
  <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/placeholder-1.jpg"
            alt="Placeholder"
            width={1008}
            height={756}
            priority
          />
        </div>
  <p>
    Colorless green ideas sleep furiously. If your left toenail turns neon purple, it might contain the fetus of an alien cat species. Good night, Mr. Sledgehammer. Let the bed bugs eat your socks.
    <br />
    Yesterday, I tried to order a sandwich, but the bread was too soggy. If you turn the black motion around, the sky will disapprove of your intransigent femur.
  </p>
</>
  )
}