import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Faq () {
  return (
  <>
    <Head>
      <title>FAQ</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet" />
    </Head>
    <h1 > Frequently Asked Questions (FAQ) </h1>
    <ul>
      <li>
        <h3 className={styles.faq}>Q. Is water wet?</h3>
        <h4>A. Pylons are dry.</h4>
      </li>

      <li>
        <h3 className={styles.faq}>Q. Is mac and cheese available for purchase?</h3>
        <h4>A. It is only if you donate belly button lint.</h4>
      </li>

      <li>
        <h3 className={styles.faq}>Q. Did Luigi Russolo have an udder protruding from his left kneecap?</h3>
        <h4>A. What do you think?</h4>
      </li>

      <li>
        <h3 className={styles.faq}>Q. Where can I buy witchcraft supplies in advance of the festival?</h3>
        <h4>A. You can find each of our vendors underneath either stage.</h4>
      </li>

      <li>
        <h3 className={styles.faq}>Q. Does it hurt the horse?</h3>
        <h4>No.</h4>
      </li>
    </ul>
  </>
  )
}